Repository thinkfiveable/open, pull requests merged in 2021-03, with the labels that each got.

#7 Create MIT LICENSE
  LICENSE
Labels: documentation

#9 add default system theme to ThemeProvider and configure Tailwind and add Hero and add Card component
  components/card.js
  components/nav.js
  pages/_app.js
  pages/index.js
  public/favicon.ico
  styles/globals.css
  tailwind.config.js
Labels: t: feature

#12 chore: contributor guidelines
  .github/CODE_OF_CONDUCT.md
  CONTRIBUTING.md
Labels: p: low, t: meta

#14 chore: enforce commit convention
  CONTRIBUTING.md
  README.md
  package-lock.json
  package.json
Labels: p: medium, t: meta

#13 ci: lint and build workflows
  .eslintrc.js
  .github/workflows/build.yml
  .github/workflows/lint.yml
  .prettierrc
  CONTRIBUTING.md
  README.md
  components/card.js
  components/head.js
  components/nav.js
  lib/fetcher.js
  next-env.d.ts
  package-lock.json
  package.json
  pages/_app.js
  pages/api/hello.js
  pages/index.js
  postcss.config.js
  tailwind.config.js
  tsconfig.eslint.json
  tsconfig.json
Labels: good first issue, p: high, t: feature

#23 feat: create card component
  components/card.js
  pages/index.js
Labels: p: medium, t: feature

#31 docs: basic overview of git workflow
  git-tutorials/git.md
Labels: p: high, s: wip, t: documentation
