Repository thinkfiveable/open, pull requests merged in 2021-04, with the labels that each got.

#34 chore: submission guidelines
  SUBMISSION_GUIDELINES.md
Labels: semver: minor, t: meta

#24 feat: new footer component
  components/footer.js
  pages/index.js
  styles/globals.css
Labels: p: high, semver: minor, t: feature

#41 feat: render base data
  data/PROJECTS.json
  pages/index.js
Labels: p: high

#40 chore: general cleanup
  .eslintrc.js
  .prettierrc
  components/MDXComponents.js
  components/card.js
  components/layout.js
  package-lock.json
  package.json
  pages/about.mdx
  pages/index.js
Labels: p: medium

#46 meta: add project submission batch
  data/PROJECTS.json
Labels: !: Submission

#47 refactor: index
  components/card.js
  data/PROJECTS.json
  pages/index.js
Labels: p: medium

#52 fix card images & add links
  components/card.js
  components/layout.js
  data/PROJECTS.json
  package-lock.json
  pages/index.js
Labels: p: low, 🏷️t: feature

#51 feat: git tutorials page
  components/layout.js
  pages/docs/git.mdx
Labels: ❗p: medium, 🏷️t: feature

#56 remove git switch info
  pages/docs/git.mdx
Labels: p: low, 🏷️t: documentation

#55 feat: add module caching
  .github/workflows/build.yml
  .github/workflows/lint.yml
Labels: p: low, 🏷️t: ci/cd

#54 fix: search card broken images
  components/card.js
  components/searchcard.js
  pages/search.js
Labels: ❗p: medium, 🏷️t: bugfix
