Repository thinkfiveable/open, pull requests merged in 2021-05, with the labels that each got.

#62 fix: add class [focus:outline-none]
  components/searchbar.js
Labels: p: low, 🏷️t: bugfix

#65 feat: contributor component
  components/contributor.js
  components/footer.js
  components/layout.js
  pages/contributors.mdx
  pages/index.js
  tailwind.config.js
Labels: ❗p: medium, 🏷️t: feature

#72 chore: add rent-a-ni.co submission
  data/PROJECTS.json
Labels: 🏷️t: Submission
